
analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    file_names: ignore
    library_prefixes: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    non_constant_identifier_names: ignore
    unnecessary_lambdas: ignore
    unnecessary_null_comparison: ignore
    unused_element: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore


include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_typing_uninitialized_variables
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - avoid_unused_constructor_parameters
    - unnecessary_lambdas
