name: quran_time
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_local_notifications: ^19.4.0
  google_fonts: ^6.2.1
  quran: ^1.3.3
  shared_preferences: ^2.2.3
  timezone: ^0.10.1
  workmanager: ^0.9.0+2
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: ^0.20.2
  flutter_styled_toast: ^2.2.1
  dropdown_button2: ^2.3.9
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/CairoPlay-Regular.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/theming

flutter_intl:
  enabled: true
